services:
  - type: web
    name: tvp-pdf-converter
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
    healthCheckPath: /health
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*"
      ignoredPaths:
        - "*.md"
        - ".gitignore" 
